import React from "react";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function ContentLayout({ children, }: { children: React.ReactNode }) {
    return (
        <div>
            <div className={"absolute right-12"}>
                <p className={"opacity-55 text-sm text-green-500"}>Content Layout</p>
            </div>
            {children}
        </div>
    )
}
