import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import React from "react";
import Nav from "@/app/components/Nav";

const inter = localFont({
    src: './public/Inter.ttf',
    display: 'swap',
    variable: "--font-inter"
})

export const metadata: Metadata = {
    title: "Aotearoa Airborne Pollen Collective",
    description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={inter.variable}>
            <Nav/>
            <div className={"w-[1080px] px-6 mx-auto"}>
                {children}
            </div>
        </body>
        </html>
    )
}
