import React from "react";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function HomepageLayout({ children, }: { children: React.ReactNode }) {
    return (
        <div>
            {children}
        </div>
    )
}
