name: Backend - Deploy (Development)
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_DEV_ID }}
on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'

jobs:
  backend-deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        working-directory: ./backend
        run: |
          npm install --global vercel@canary
      - name: Pull, Build & Deploy
        working-directory: ./backend
        run: |
          npm ci
          npm run build
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
