name: Backend (Development)
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_DEV_ID }}
on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create env File
        working-directory: ./backend
        run: |
          touch .env
          echo ENV=DEV >> .env
          echo PORT=3000 >> .env
          echo MONGO_URI="${{ secrets.MONGO_URI_DEV }}" >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET_DEV }} >> .env
          echo COGNITO_CLIENT_ID=${{ secrets.COGNITO_CLIENT_ID }} >> .env
          echo COGNITO_USERPOOL_ID=${{ secrets.COGNITO_USERPOOL_ID }} >> .env
          echo BREVO_CLIENT_EMAIL=${{ secrets.BREVO_CLIENT_EMAIL }} >> .env
          echo BREVO_CLIENT_PASSWORD=${{ secrets.BREVO_CLIENT_PASSWORD }} >> .env
      - name: Install Vercel CLI
        working-directory: ./backend
        run: |
          npm install --global vercel@canary
      - name: Pull, Build & Deploy
        working-directory: ./backend
        run: |
          npm ci
          npm run build
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
