name: Backend - Deploy (Production)
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROD_ID }}
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create env File
        working-directory: ./backend
        run: |
          touch .env
          echo ENV=PROD >> .env
          echo PORT=3000 >> .env
      - name: Install Vercel CLI
        working-directory: ./backend
        run: |
          npm install --global vercel@canary
      - name: Pull, Build & Deploy
        working-directory: ./backend
        run: |
          npm ci
          npm run build
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
