name: End-to-end Tests
on:
  push:
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'cypress/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: |
            npm run install
            npm run dev
            sleep 10
