name: End-to-end Tests
on:
  push:
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'cypress/**'
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Start Backend
        run: |
          cd backend
          npm ci
          npm run dev
      - name: Start Frontend
        run: |
          cd frontend
          npm ci
          npm run dev
      - name: Run Cypress
        uses: cypress-io/github-action@v6
